/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedAssetsRouteImport } from './routes/_authed/assets'
import { Route as AuthedDraftsRouteImport } from './routes/_authed/drafts'
import { Route as AuthedFactsRouteImport } from './routes/_authed/facts'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTasksRouteImport } from './routes/_authed/tasks'
import { Route as AuthedTemplatesRouteImport } from './routes/_authed/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAssetsRoute = AuthedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDraftsRoute = AuthedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFactsRoute = AuthedFactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksRoute = AuthedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTemplatesRoute = AuthedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AuthedAssetsRoute
  '/drafts': typeof AuthedDraftsRoute
  '/facts': typeof AuthedFactsRoute
  '/settings': typeof AuthedSettingsRoute
  '/tasks': typeof AuthedTasksRoute
  '/templates': typeof AuthedTemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AuthedAssetsRoute
  '/drafts': typeof AuthedDraftsRoute
  '/facts': typeof AuthedFactsRoute
  '/settings': typeof AuthedSettingsRoute
  '/tasks': typeof AuthedTasksRoute
  '/templates': typeof AuthedTemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/assets': typeof AuthedAssetsRoute
  '/_authed/drafts': typeof AuthedDraftsRoute
  '/_authed/facts': typeof AuthedFactsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/tasks': typeof AuthedTasksRoute
  '/_authed/templates': typeof AuthedTemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/drafts'
    | '/facts'
    | '/settings'
    | '/tasks'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/drafts'
    | '/facts'
    | '/settings'
    | '/tasks'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/assets'
    | '/_authed/drafts'
    | '/_authed/facts'
    | '/_authed/settings'
    | '/_authed/tasks'
    | '/_authed/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/assets': {
      id: '/_authed/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthedAssetsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/drafts': {
      id: '/_authed/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthedDraftsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/facts': {
      id: '/_authed/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof AuthedFactsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks': {
      id: '/_authed/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthedTasksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/templates': {
      id: '/_authed/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthedTemplatesRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAssetsRoute: typeof AuthedAssetsRoute
  AuthedDraftsRoute: typeof AuthedDraftsRoute
  AuthedFactsRoute: typeof AuthedFactsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTasksRoute: typeof AuthedTasksRoute
  AuthedTemplatesRoute: typeof AuthedTemplatesRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAssetsRoute: AuthedAssetsRoute,
  AuthedDraftsRoute: AuthedDraftsRoute,
  AuthedFactsRoute: AuthedFactsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTasksRoute: AuthedTasksRoute,
  AuthedTemplatesRoute: AuthedTemplatesRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
